# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phase_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_images', models.IntegerField(help_text='Number of images of existing problems')),
                ('problem_images_upload', models.ImageField(upload_to='phase_1_images')),
            ],
        ),
    ]
