# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text="Member's name", max_length=50)),
                ('member_email', models.EmailField(help_text="Member's Email ID", max_length=50)),
                ('member_contact', models.IntegerField(help_text="Member's Contact Number")),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Enter your team name', max_length=50)),
                ('total_members', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='1', help_text='Total Team Members')),
                ('city', models.CharField(help_text='City/Town', max_length=200)),
                ('state', models.CharField(help_text='State', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_register.Team'),
        ),
    ]
