# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text="Member's name", max_length=50)),
                ('member_email', models.EmailField(help_text="Member's Email ID", max_length=50)),
                ('member_contact', models.IntegerField(help_text="Member's Contact Number")),
                ('docfile', models.ImageField(upload_to='documents/%Y/%m/%d')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_register.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='team',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
