# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0002_auto_20170527_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='docfile',
            new_name='id_proof',
        ),
    ]
