# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0004_remove_member_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_proof',
            field=models.ImageField(upload_to='ID_proofs'),
        ),
    ]
